import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import LogoImg from "@/public/logo.png";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SemWeb Football",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="">
          <div className="container mx-auto py-2">
            <Link href="/" className="flex flex-row items-center justify-items-center">
              <Image src={LogoImg} alt="ball" width={40} height={40} />
              <p className="ml-2 font-medium text-xl">SemWeb Football</p>
            </Link>
          </div>
        </header>
        <main>
          <div className="max-w-screen-lg mx-auto py-5">{children}</div>
        </main>
      </body>
    </html>
  );
}
